language: cpp

compiler: gcc

script:
    - make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QiqL4VDwf3+OLv6x1qqqdTJFrclf8IObxgh1N9+O9fB6R1BAla9ul93e5yufDyR3wcEtcQDymKGTa+oTK5Dw4v1XCLd83l6fd+ZzaFiOdFLGBO+cVySBE0/LKQ+Js5c85UqwbeqXodgUqEu1FjoJLq0H3EG9NqdH8/6rEvhQEkSckBGizQOGkc6NLFsRymstgNgFL/0+HfHvzwnsCmdBHlSag+8m93Yc5CCPqJoGakuS1jko4C7YuWQO6DZGnyBaUSXv52bWwqty5n+BkKbIFOApzUHzQPUnINyWj5LoPOflr1s+23euXM5LZHQw1YouUUlnn7+UKmgEqjF62dj4gdDTVd4aeoGEDpbrOS+H6GNRJK+jja2bqAMwyneEUsjTv/3Rqu+MOgcJMDH8PFsjdKVuVqYnAWBLf7Jo6mnTl3gH7UfpWfjdr2kz1cAmiVhutJLRHl6nugyLcchh5wsmb8vluKjhraQ9ndD5RY/bgo0TVekxyza/guOt21aROKtWJc6G54pWMd67ZkKI2KyDZwd1Dzi0tBZpQtb/mlNPqw7ToqLezY/QWv6EeBVqa3dFtIYEIUjrQqoUR4zXhpYAtAcjNFJL9Fau+vQtQlCf8TRhHeCjp+F7Ut6IrtZdw7DxEXEkGfQF02LkB5Sfb+qVX7GaboUBhg7yclM+jHeQx00="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "parag0nal/first-json"
      description: "<Your project description here>"
    notification_email: yuxuancai4@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan
